#!/bin/bash
echo "📱 Buscando crash logs de LessMo..."
echo ""
echo "Por favor:"
echo "1. Conecta tu iPhone a la Mac"
echo "2. Ve a: Ajustes → Privacidad → Analítica y mejoras → Datos analíticos"
echo "3. Busca archivos que empiecen con 'LessMo'"
echo "4. Toca el archivo más reciente"
echo "5. Toca el botón de compartir (arriba derecha)"
echo "6. Guárdalo y súbelo aquí"
echo ""
echo "O desde Mac:"
echo "- Abre Consola.app"
echo "- Conecta el iPhone"
echo "- Selecciona tu iPhone en la barra lateral"
echo "- Filtra por 'LessMo' o 'crash'"
